name: Dev
values:
  - key: baseUrl
    value: "https://<dev-api-url>"
  - key: authUsername
    value: "devuser"
  - key: authPassword
    value: "DevPassword123456"
  - key: authToken
    value: ""
  - key: customerId
    value: "1"
  - key: projectId
    value: "1"
